### PR TITLE
Shared Button Added

### PR DESCRIPTION
**Pull request by pcabreram1234**

### CODE REVIEW

**Review by itsalb3rt — CHANGES_REQUESTED** [review]
- Please don't change the `.env.example` file, revert the changes in this file.
- Remove the `package-lock.json`, this project uses yarn, no NPM
- Revert the changes of the `src/router/routes.js` file, I see some changes of quotes, from single to double.
- Revert the changes of the `quasar.config.js` file, I see some changes of quotes, from single to double.

After you make all the changes, I continue testing it.

**Comment by pcabreram1234** [comment]
Chages Done, please check and any issue do not doubt to ask me.

**Comment by itsalb3rt** [comment]
No delete the files, revert each file to the commit with the hash `9666349fd870adfa3f2cb09256a020fe3d1cd81d` note the comment and check this doc how to [https://dev.to/lofiandcode/git-and-github-how-to-revert-a-single-file-dha](https://dev.to/lofiandcode/git-and-github-how-to-revert-a-single-file-dha)

> * Please don't change the `.env.example` file, revert the changes in this file.
> * Remove the `package-lock.json`, this project uses yarn, no NPM
> * Revert the changes of the `src/router/routes.js` file, I see some changes of quotes, from single to double.
> * Revert the changes of the `quasar.config.js` file, I see some changes of quotes, from single to double.
> 
> After you make all the changes, I continue testing it.

**Comment by itsalb3rt** [comment]
I'm testing the functionality and get this error;

image


Others considerations:
- Add the `push` prop to the button to following the UI guidelines #2 
- Make the `Share` button `float` to the `right` to no leave an empty line between the card container and the photo of the space

**Comment by pcabreram1234** [comment]
It is mandatory to use the Share VueVueSocialSharing Plugin, therefore I have to modify the `.quasar/app.js` file

The change I have to do is this.

`import VueSocialSharing from 'vue-social-sharing'`
`Vue.use(VueSocialSharing)`

And after the line `app.use(Quasar, quasarUserOptions)`
add this `app.use(VueSocialSharing)`

Only with this the social media button will works.

exist another way to load this plugin without to modify  the `.quasar/app.js` file ?

I will waiting for your opinion and recomendations

**Comment by itsalb3rt** [comment]
> VueVueSocialSharing

No problem 😃 , you can import the component in the same file you can use it, for example;

```javascript
// buttons component
import VueSocialSharing from 'vue-social-sharing'
// others imports and code

{
components: {VueSocialSharing }
}
```

and now you can use in line component;

```html
<template>
  <VueSocialSharing props... />
</template>
```

**Comment by pcabreram1234** [comment]
Oh you are rigth, I have forgotten that. I need to practice more VueJs. thanks @itsalb3rt later I will prove this.

**Comment by itsalb3rt** [comment]
> 

don't worry Phillip we are here to help 😃

**Comment by pcabreram1234** [comment]
I just made the changes required. Please when you have time review it

**Review by itsalb3rt — APPROVED** [review]

**Comment by itsalb3rt** [comment]
Thanks @pcabreram1234 I really appreciate this ❤️

**Pull request merged**
